version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "ruby"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      cargo-ruby-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "ql"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      cargo-ql-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch', 'version-update:semver-minor']
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "go/extractor"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    allow:
      - dependency-name: "golang.org/x/mod"
      - dependency-name: "golang.org/x/tools"
    groups:
      extractor-dependencies:
        patterns:
          - "golang.org/x/*"
    reviewers:
      - "github/codeql-go"

  - package-ecosystem: "gomod"
    directory: "go/ql/test"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
    reviewers:
      - "github/codeql-go"
    groups:
      gomod-test-dependencies:
        patterns:
          - "*"
